### PR TITLE
#81: Add github action to publish to PyPI.

### PR DESCRIPTION
**Pull request by perrygoy**
I think this will work, maybe. I'm not sure. Let's find out!

This PR adds a new Github Action to publish ScreenPy to PyPI when a new tag is pushed up. Historically i've only published a new tag during the deployment process, so this ties in nicely with the typical tagging procedure we've followed on ScreenPy. Plus, now we can cut new versions just by pushing a new tag!

### CODE REVIEW

**Comment by langgaibo** [comment]
I was gonna say it looks good to me, but it also failed a check

**Comment by perrygoy** [comment]
> I was gonna say it looks good to me, but it also failed a check

Yeah, it failed the check that it added. 😩 

The error message is not very informative so i'm not 100% sure how to figure out what went wrong, but my guess is that i set up PyPI's trusted publisher incorrectly. I'll double check that and give it another shot.

**Comment by perrygoy** [comment]
... oh duh, i didn't set up the trusted publisher on Test PyPI. 🤦

**Comment by perrygoy** [comment]
Success! https://github.com/ScreenPyHQ/screenpy/actions/runs/4888893509

**Review by langgaibo — APPROVED** [review]
Looks good to me 😏

**Pull request merged**
